version: '3.1'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: serverless-ilia-wallet
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_URL=$DB_URL
      - JWT_SECRET=$JWT_SECRET
      - USER_DB=$USER_DB
    ports:
      - 3001:3001
      - 50051:50051
    volumes:
      - .:/usr/app
    networks:
      - ilia-network
  mongo-wallet:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - ilia-network
networks:
  ilia-network:
    driver: bridge
